name: release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bump version & push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          default_bump: minor
          tag_prefix: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: create github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
          body: ${{ steps.tag_version.outputs.changelog }}